# Generated by Django 4.2.21 on 2025-05-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_takenbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Телефон',
            new_name='phone',
        ),
    ]
